app-template:
  defaultPodOptions:
    enableServiceLinks: false

  controllers:
    main:
      containers:
        main:
          image:
            repository: hub.docker.com/openproject/openproject
            tag: 17
          env:
            - SECRET_KEY_BASE: secret
            - OPENPROJECT_HOST__NAME: localhost:8080
            - OPENPROJECT_HTTPS: false
            - OPENPROJECT_DEFAULT__LANGUAGE: en
  service:
    main:
      controller: main
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "mealie"
      ports:
        http:
          port: 80
          targetPort: 8080

  persistence:
    # SQLite database and app data
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /var/openproject/assets
