---
apiVersion: v2
name: tailscale-operator
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: tailscale-operator
  version: 1.90.8
  repository: https://pkgs.tailscale.com/helmcharts
