app-template:
  defaultPodOptions:
    enableServiceLinks: false

  env:
    - name: ALLOWED_ORIGINS
      value: "https://vcom.dev"

  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/swatfish/skybrief-backend
            tag: latest
          env:
  service:
    main:
      controller: main

  persistence:
    # SQLite database and app data
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /app/data
  ingress:
    # Frontend ingress with SSL
    frontend:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: skybrief-backend.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: frontend
                port: http
      tls:
        - secretName: skybrief-backend-tls
          hosts:
            - skybrief-backend.intropin.be
